### ISSUE TITLE
Config.properties file name and path should be configurable

### ISSUE THREAD

**Issue by hexwit** [imagekit-developer/imagekit-java#10]
Currently there is no way how to define another file for loading configuration. 
This should be configurable. Or just accept Properties object.

**Comment by imagekitio** [comment]
Hi @hexwit ,

Let me know if this works for you.

Create a new configuration
```java
import io.imagekit.sdk.ImageKit;
import io.imagekit.sdk.config.Configuration;
Configuration config=new Configuration(publicKey, privateKey, urlEndpoint);
imageKit.setConfig(config);
```
