### ISSUE TITLE
Failure while Instantiating ImageKit

### ISSUE THREAD

**Issue by chriseteka** [imagekit-developer/imagekit-java#23]
I'll start by commending your efforts, nice work guys. 

I recently upgraded to version `2.0.0`, and noticed my application no longer compiles. Turns out that the method returning the image kit singleton `ImageKit.getInstance()` doesn't initialize the instance properly. 

It fails with the error: `Invocation of init method failed; nested exception is java.lang.NoSuchFieldError: Companion`.

A little dig into the implementation revealed that `OkHttpClient` was the cause, it is in fact the class that wasn't instantiating properly. The error from `OkHttpClient` propagates to your `RestClient` class and then to the class responsible for creating ImageKit.

I had to work around this in my `pom.xml` to get my application running again. Below is the workaround I applied:
```xml
<dependency>
    <groupId>com.github.imagekit-developer</groupId>
    <artifactId>imagekit-java</artifactId>
    <version>2.0.0</version>
    <exclusions>
        <exclusion>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-gson</artifactId>
        </exclusion>
        <exclusion>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp:</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>5.0.0-alpha.10</version>
</dependency>
```

I am not sure if I am doing something wrong, or if there is a change from the old implementation that may have caused this error. I'll appreciate you having a look at this implementation again and advising accordingly.

Thank you.

**Comment by amanforindia** [comment]
@chriseteka this seems probably due to imagekit using okhttp3 v3 and your project using okhttp3 v4. We're looking into it and will keep you posted.

**Comment by amanforindia** [comment]
@imagekitio we tested with okhttp3 v4 in a new project and the upload API seems to be working fine without the need for an exclusion. @chriseteka were you able to solve this?

**Comment by imagekitio** [comment]
@chriseteka we are closing this issue now, but if it doesn't work for you please provide more information and re-open it.

**Comment by mohammadehtesham-mobin** [comment]
Same Issue happened with me , and it worked with workarround
