### ISSUE TITLE
Error while uploading file using Java SDK. UnknownException: stream was reset: FLOW_CONTROL_ERROR

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-java#28]
Issue seems to be arising from okhttp library used by Java SDK. Error is thrown when more data (bytes) is sent to the library than it can handle. (see attached image which shows the image thrown by the library).

<img width="1440" alt="Screenshot 2023-02-07 at 5 15 01 PM" src="https://user-images.githubusercontent.com/45416977/218640586-e2cc4bee-8289-45e2-8acb-d7f52d09f658.png">

**Comment by ngyongzhen** [comment]
Hi what's the file type and file size you tried to upload with?

**Comment by niveditn** [comment]
Hi @ngyongzhen, here is some additional information about the issue:
- File size – around ~400-500 KB
- File type –  typically JPG
- SDK versions tried – 1.0.1, 2.0.0
- Reported successful upload of 5 or 10 images sequentially, after which the upload error occurs with `UnknownException: stream was reset: FLOW_CONTROL_ERROR`
- Sometimes the success rate is around 50%

**Comment by imagekitio** [comment]
Please provide the minimum code and setup to reproduce this issue and re-open the issue.
