### ISSUE TITLE
The build seems broken?

### ISSUE THREAD

**Issue by jayb0b** [imagekit-developer/imagekit-java#3]
I followed the steps for Maven: added jitpack and added 1.0.1 as a dependency in my POM. However, i get java.lang.NoClassDefFoundError for ImageKit.class. Looking at the Maven dependecies, there was hardly anything in there just the sample app and not the sdk. 

If you search for the project on jitpack, it suggests a different maven dependency. That didn't work either. 

I tried version 1.0.0 and this DOES give me the SDK... but also has missing dependecies: the first one that came up was  okhttp3.OkHttpClient.

**Comment by jayb0b** [comment]
The workaround I've found with 1.0.0 is to add in okhttp3.OkHttpClient as an additional dependecy in my project. 1.0.1 doesn't seem to work at all.

**Comment by ansidev** [comment]
@imagekitio The reason is you are importing libs manually instead of fetching them from mvn repository. Please fix it asap.

**Comment by hexwit** [comment]
My setup is also didn't work. The same error.

**Comment by imagekitio** [comment]
@ansidev @jayb0b @hexwit can you please check and try version 2.0.0?
