### ISSUE TITLE
Remove sdk version from the an url

### ISSUE THREAD

**Issue by kirillsbarsukov** [imagekit-developer/imagekit-java#9]
Hi guys! 
Is there any way to remove sdk sign from the url
`https://ik.imagekit.io/your_imagekit_id/default-image.jpg?tr=w-400,h-600**&ik-sdk-version=java-1.0.3**`
Unfortunately, I have not find an answer to my question in the documentation section

**Comment by imagekitio** [comment]
Hi @KirillSBarsukov, at the moment there is no way to do it within the SDK. It is always added as a query parameter and does not interfere with the image fetch. Is there any specific reason you want to remove this?

**Comment by imagekitio** [comment]
`ik-sdk-version` is removed in v 2.0.0

**Comment by SarvagyaVaish** [comment]
Are the `ik-sdk-version` and `updatedAt` critical? What's their purpose?
